name: Java CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'
      - name: install Ant
        run: ant -lib C:/Users/salma/.ant/lib war
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml dist
  
      
      
#  test:
#     name: Running Units Tests
#     runs-on: ubuntu-latest
#     needs: build

#     steps:
#     - uses: actions/checkout@v1
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v1
#       with:
#         node-version: ${{ matrix.node-version }}
#     - name: Test
#       run: javac -cp junit-4.13.jar;hamcrest-core-1.3.jar;. org.junit.runner.JUnitCore Tetris
      
