name: GitHub Actions Demo

on:
  pull_request:
  push:
    branches: 
      - master

jobs:
 build:
    name: Build prj
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: javac -d bin/ -classpath lib/commons-lang3-3.5.jar src/fr/ubo/tetris/*.java
    - name: Inside bin
      run: cd bin
    - name: jar file
      run: jar -cf ./fr/Tetris.jar fr/ubo/tetris/*
    - name: Execute prj
      run: java -cp ./fr/Tetris.jar;../lib/commons-lang3-3.5.jar fr.ubo.tetris.Tetris
      
 test:
    name: Running Units Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test
      run: javac -cp junit-4.13.jar;hamcrest-core-1.3.jar;. org.junit.runner.JUnitCore Tetris
      
